### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by DominikReber** [wooooooak/DonutGaugeView#1]
Hello

Not an issue I guess but I am unable to implement this.
Using newest Android Studio.

project.gradle:

    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }

Module gradle:

dependencies {
.......Others
   implementation 'com.github.wooooooak:DonutGuageView:1.0.4'
}

Then sync.

Then add code to xml?
Doesn't recognize

**Comment by wooooooak** [comment]
I think it's because of the gradle version.
I've upgraded the version, so try again with 1.0.8 or 1.0.9.

**Comment by gitpushyj** [comment]
@DominikReber 

I think it's because of the gradle version.
I've upgraded the version, so try again with 1.0.8 or 1.0.9.

**Comment by DominikReber** [comment]
Ah the problem was that in your sample text which I copied, you had 
implementation 'com.github.wooooooak:DonutGuageView:1.0.4'
instead of
implementation 'com.github.wooooooak:DonutGaugeView:1.0.4'

(typo Guage/Gauge :-p)

Working now, thanks
